/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCallC */

#ifndef _Included_JavaCallC
#define _Included_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCallC
 * Method:    strOut
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JavaCallC_strOut
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
